# Q* Learning with FrozenLake 🕹️⛄

In this Notebook, we'll implement an agent <b>that plays FrozenLake.</b>

The goal of this game is <b>to go from the starting state (S) to the goal state (G)</b> by walking only on frozen tiles (F) and avoid holes (H).However, the ice is slippery, <b>so you won't always move in the direction you intend. (stochastic environment)

In [1]:
%%html
<img src="img/frozenlake.png", width=300 ,height=400>

🆕📜📹👹👾📚👨‍💻📧🌐🙌🏗️🚕⚙️🗄️🎮🕹️⛄

## Step 0: Import dependencies 📚
    We use 3 libraries:
   - `Numpy` for our Qtable
   - `OpenAI Gym` for our FrozenLake Environment
   - `Random` to generate random numbers

In [2]:
import numpy as np
import gym
import random

## Step 1: Create the environment 🎮
   - Here we will create the FrozenLake environment. 
   - OpenAI Gym is a library composed of many environments that we can use to train our agents.
   - In our case we choose to use Frozen Lake.

In [3]:
env = gym.make('FrozenLake-v0')

## Step 2: Create the Q-table and initialize it 🗄️
   - Now, we'll create our Q-table, to know how much rows (states) and columns (actions) we need, we need to calculate the action_size and the state_size.
   - OpenAI Gym provides us a way to do that: `env.action_space.n` and `env.observation_space.n`

In [4]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [5]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Step 3: Create the hyperparameters ⚙️

In [6]:
episodes = 15000
steps = 99

alpha = 0.8
gamma =0.95

epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.01

## Step 4: The Q learning algorithm 👨‍

In [7]:
rewards = []

for e in range(episodes):
    state = env.reset()
    s = 0
    done = False
    for s in range(steps):
        exp_exp = np.random.uniform(0,1)
        if exp_exp > epsilon:
            action = np.argmax(qtable[state, :])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        qtable[state, action] = qtable[state, action] + alpha*(reward + gamma*np.max(qtable[new_state,:] - qtable[state, action]))
        
        state = new_state
        reward += reward
        rewards.append(reward)
        if done:
            break
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate * e)
print('the score : {}'.format(sum(rewards)/episodes))
print(qtable)

the score : 0.00013333333333333334
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.8]
 [0.  0.  0.  0. ]]


## Step 5: Use our Q-table to play FrozenLake ! 👾
  - After 10000 episodes, The Q-table can be used as a \"cheatsheet\" to play \"FrozenLake.\"
  - By running this cell you can see our agent playing FrozenLake.

In [8]:
env.reset()
for e in range(episodes):
    state = env.reset()
    done =False
    s = 0
    for s in range(steps):
        action = np.argmax(qtable[state,:])
        new_state, reward, done, info = env.step(action)
        state = new_state
        #env.render() # if you guys want to see visual rendering uncomment this line!
        if done:
            print("Number of steps: {}".format(s))
            break
env.close()            

Number of steps: 28
Number of steps: 32
Number of steps: 41
Number of steps: 10
Number of steps: 4
Number of steps: 6
Number of steps: 42
Number of steps: 3
Number of steps: 7
Number of steps: 22
Number of steps: 17
Number of steps: 4
Number of steps: 38
Number of steps: 47
Number of steps: 18
Number of steps: 24
Number of steps: 8
Number of steps: 29
Number of steps: 7
Number of steps: 4
Number of steps: 18
Number of steps: 11
Number of steps: 11
Number of steps: 17
Number of steps: 11
Number of steps: 6
Number of steps: 8
Number of steps: 4
Number of steps: 17
Number of steps: 14
Number of steps: 6
Number of steps: 41
Number of steps: 8
Number of steps: 9
Number of steps: 7
Number of steps: 24
Number of steps: 27
Number of steps: 49
Number of steps: 17
Number of steps: 7
Number of steps: 6
Number of steps: 27
Number of steps: 10
Number of steps: 37
Number of steps: 25
Number of steps: 17
Number of steps: 6
Number of steps: 2
Number of steps: 2
Number of steps: 40
Number of steps: 5
N

Number of steps: 46
Number of steps: 16
Number of steps: 21
Number of steps: 16
Number of steps: 8
Number of steps: 9
Number of steps: 21
Number of steps: 8
Number of steps: 20
Number of steps: 27
Number of steps: 31
Number of steps: 10
Number of steps: 39
Number of steps: 3
Number of steps: 11
Number of steps: 12
Number of steps: 43
Number of steps: 18
Number of steps: 57
Number of steps: 7
Number of steps: 2
Number of steps: 2
Number of steps: 14
Number of steps: 4
Number of steps: 39
Number of steps: 6
Number of steps: 5
Number of steps: 3
Number of steps: 18
Number of steps: 23
Number of steps: 31
Number of steps: 6
Number of steps: 11
Number of steps: 59
Number of steps: 24
Number of steps: 16
Number of steps: 6
Number of steps: 25
Number of steps: 15
Number of steps: 8
Number of steps: 32
Number of steps: 15
Number of steps: 16
Number of steps: 10
Number of steps: 16
Number of steps: 4
Number of steps: 2
Number of steps: 23
Number of steps: 57
Number of steps: 16
Number of steps:

Number of steps: 11
Number of steps: 5
Number of steps: 9
Number of steps: 2
Number of steps: 17
Number of steps: 36
Number of steps: 5
Number of steps: 9
Number of steps: 17
Number of steps: 37
Number of steps: 16
Number of steps: 6
Number of steps: 15
Number of steps: 2
Number of steps: 15
Number of steps: 7
Number of steps: 10
Number of steps: 59
Number of steps: 11
Number of steps: 5
Number of steps: 9
Number of steps: 19
Number of steps: 20
Number of steps: 2
Number of steps: 36
Number of steps: 56
Number of steps: 22
Number of steps: 9
Number of steps: 52
Number of steps: 6
Number of steps: 10
Number of steps: 40
Number of steps: 8
Number of steps: 26
Number of steps: 52
Number of steps: 2
Number of steps: 35
Number of steps: 3
Number of steps: 7
Number of steps: 2
Number of steps: 45
Number of steps: 4
Number of steps: 11
Number of steps: 39
Number of steps: 8
Number of steps: 34
Number of steps: 8
Number of steps: 2
Number of steps: 10
Number of steps: 18
Number of steps: 22
Nu

Number of steps: 21
Number of steps: 17
Number of steps: 29
Number of steps: 53
Number of steps: 39
Number of steps: 6
Number of steps: 3
Number of steps: 12
Number of steps: 3
Number of steps: 12
Number of steps: 2
Number of steps: 32
Number of steps: 16
Number of steps: 8
Number of steps: 17
Number of steps: 33
Number of steps: 17
Number of steps: 5
Number of steps: 20
Number of steps: 18
Number of steps: 3
Number of steps: 7
Number of steps: 5
Number of steps: 45
Number of steps: 9
Number of steps: 11
Number of steps: 15
Number of steps: 25
Number of steps: 32
Number of steps: 11
Number of steps: 14
Number of steps: 3
Number of steps: 12
Number of steps: 6
Number of steps: 31
Number of steps: 18
Number of steps: 26
Number of steps: 29
Number of steps: 33
Number of steps: 2
Number of steps: 10
Number of steps: 22
Number of steps: 19
Number of steps: 29
Number of steps: 29
Number of steps: 4
Number of steps: 6
Number of steps: 6
Number of steps: 11
Number of steps: 25
Number of steps:

Number of steps: 17
Number of steps: 13
Number of steps: 29
Number of steps: 3
Number of steps: 4
Number of steps: 18
Number of steps: 11
Number of steps: 23
Number of steps: 6
Number of steps: 20
Number of steps: 4
Number of steps: 6
Number of steps: 3
Number of steps: 27
Number of steps: 4
Number of steps: 4
Number of steps: 15
Number of steps: 15
Number of steps: 3
Number of steps: 9
Number of steps: 6
Number of steps: 9
Number of steps: 4
Number of steps: 10
Number of steps: 21
Number of steps: 50
Number of steps: 29
Number of steps: 13
Number of steps: 50
Number of steps: 19
Number of steps: 8
Number of steps: 3
Number of steps: 11
Number of steps: 45
Number of steps: 17
Number of steps: 24
Number of steps: 28
Number of steps: 12
Number of steps: 4
Number of steps: 2
Number of steps: 28
Number of steps: 30
Number of steps: 13
Number of steps: 8
Number of steps: 18
Number of steps: 24
Number of steps: 7
Number of steps: 16
Number of steps: 19
Number of steps: 26
Number of steps: 11

Number of steps: 47
Number of steps: 25
Number of steps: 95
Number of steps: 24
Number of steps: 9
Number of steps: 6
Number of steps: 21
Number of steps: 42
Number of steps: 10
Number of steps: 45
Number of steps: 18
Number of steps: 11
Number of steps: 18
Number of steps: 4
Number of steps: 8
Number of steps: 31
Number of steps: 20
Number of steps: 15
Number of steps: 11
Number of steps: 10
Number of steps: 16
Number of steps: 10
Number of steps: 8
Number of steps: 29
Number of steps: 34
Number of steps: 10
Number of steps: 30
Number of steps: 56
Number of steps: 6
Number of steps: 14
Number of steps: 10
Number of steps: 19
Number of steps: 18
Number of steps: 5
Number of steps: 15
Number of steps: 8
Number of steps: 6
Number of steps: 12
Number of steps: 10
Number of steps: 8
Number of steps: 11
Number of steps: 56
Number of steps: 11
Number of steps: 13
Number of steps: 11
Number of steps: 40
Number of steps: 31
Number of steps: 34
Number of steps: 34
Number of steps: 13
Number of 

Number of steps: 35
Number of steps: 24
Number of steps: 59
Number of steps: 3
Number of steps: 8
Number of steps: 16
Number of steps: 7
Number of steps: 5
Number of steps: 18
Number of steps: 5
Number of steps: 15
Number of steps: 9
Number of steps: 8
Number of steps: 47
Number of steps: 8
Number of steps: 24
Number of steps: 24
Number of steps: 11
Number of steps: 20
Number of steps: 18
Number of steps: 4
Number of steps: 24
Number of steps: 8
Number of steps: 7
Number of steps: 23
Number of steps: 12
Number of steps: 3
Number of steps: 9
Number of steps: 6
Number of steps: 3
Number of steps: 16
Number of steps: 12
Number of steps: 34
Number of steps: 25
Number of steps: 10
Number of steps: 31
Number of steps: 63
Number of steps: 16
Number of steps: 7
Number of steps: 14
Number of steps: 12
Number of steps: 9
Number of steps: 8
Number of steps: 20
Number of steps: 9
Number of steps: 6
Number of steps: 19
Number of steps: 16
Number of steps: 15
Number of steps: 43
Number of steps: 22


Number of steps: 7
Number of steps: 2
Number of steps: 7
Number of steps: 32
Number of steps: 70
Number of steps: 8
Number of steps: 10
Number of steps: 21
Number of steps: 6
Number of steps: 7
Number of steps: 34
Number of steps: 2
Number of steps: 13
Number of steps: 26
Number of steps: 2
Number of steps: 16
Number of steps: 36
Number of steps: 6
Number of steps: 4
Number of steps: 7
Number of steps: 21
Number of steps: 33
Number of steps: 7
Number of steps: 18
Number of steps: 6
Number of steps: 16
Number of steps: 14
Number of steps: 18
Number of steps: 20
Number of steps: 24
Number of steps: 26
Number of steps: 7
Number of steps: 4
Number of steps: 22
Number of steps: 11
Number of steps: 3
Number of steps: 3
Number of steps: 26
Number of steps: 10
Number of steps: 11
Number of steps: 19
Number of steps: 11
Number of steps: 10
Number of steps: 23
Number of steps: 17
Number of steps: 18
Number of steps: 24
Number of steps: 12
Number of steps: 11
Number of steps: 13
Number of steps: 

Number of steps: 36
Number of steps: 13
Number of steps: 12
Number of steps: 28
Number of steps: 10
Number of steps: 20
Number of steps: 5
Number of steps: 26
Number of steps: 11
Number of steps: 11
Number of steps: 25
Number of steps: 26
Number of steps: 7
Number of steps: 4
Number of steps: 11
Number of steps: 59
Number of steps: 3
Number of steps: 5
Number of steps: 21
Number of steps: 27
Number of steps: 40
Number of steps: 36
Number of steps: 12
Number of steps: 16
Number of steps: 9
Number of steps: 7
Number of steps: 14
Number of steps: 11
Number of steps: 27
Number of steps: 3
Number of steps: 14
Number of steps: 2
Number of steps: 8
Number of steps: 27
Number of steps: 3
Number of steps: 31
Number of steps: 10
Number of steps: 4
Number of steps: 19
Number of steps: 20
Number of steps: 25
Number of steps: 10
Number of steps: 8
Number of steps: 3
Number of steps: 4
Number of steps: 6
Number of steps: 13
Number of steps: 16
Number of steps: 31
Number of steps: 6
Number of steps: 

Number of steps: 9
Number of steps: 25
Number of steps: 3
Number of steps: 7
Number of steps: 58
Number of steps: 24
Number of steps: 2
Number of steps: 5
Number of steps: 13
Number of steps: 9
Number of steps: 4
Number of steps: 16
Number of steps: 15
Number of steps: 21
Number of steps: 8
Number of steps: 27
Number of steps: 23
Number of steps: 45
Number of steps: 48
Number of steps: 6
Number of steps: 19
Number of steps: 5
Number of steps: 8
Number of steps: 13
Number of steps: 28
Number of steps: 5
Number of steps: 23
Number of steps: 25
Number of steps: 2
Number of steps: 2
Number of steps: 3
Number of steps: 33
Number of steps: 16
Number of steps: 18
Number of steps: 16
Number of steps: 15
Number of steps: 14
Number of steps: 7
Number of steps: 5
Number of steps: 13
Number of steps: 15
Number of steps: 30
Number of steps: 2
Number of steps: 43
Number of steps: 16
Number of steps: 6
Number of steps: 21
Number of steps: 32
Number of steps: 14
Number of steps: 53
Number of steps: 25

Number of steps: 30
Number of steps: 29
Number of steps: 9
Number of steps: 12
Number of steps: 2
Number of steps: 6
Number of steps: 6
Number of steps: 13
Number of steps: 3
Number of steps: 21
Number of steps: 10
Number of steps: 4
Number of steps: 25
Number of steps: 4
Number of steps: 7
Number of steps: 5
Number of steps: 14
Number of steps: 13
Number of steps: 10
Number of steps: 15
Number of steps: 13
Number of steps: 4
Number of steps: 8
Number of steps: 12
Number of steps: 12
Number of steps: 10
Number of steps: 18
Number of steps: 16
Number of steps: 15
Number of steps: 47
Number of steps: 33
Number of steps: 4
Number of steps: 16
Number of steps: 19
Number of steps: 9
Number of steps: 14
Number of steps: 3
Number of steps: 3
Number of steps: 20
Number of steps: 4
Number of steps: 9
Number of steps: 15
Number of steps: 15
Number of steps: 7
Number of steps: 13
Number of steps: 6
Number of steps: 23
Number of steps: 17
Number of steps: 77
Number of steps: 31
Number of steps: 6


Number of steps: 19
Number of steps: 32
Number of steps: 7
Number of steps: 17
Number of steps: 29
Number of steps: 13
Number of steps: 18
Number of steps: 22
Number of steps: 20
Number of steps: 56
Number of steps: 10
Number of steps: 10
Number of steps: 6
Number of steps: 4
Number of steps: 16
Number of steps: 13
Number of steps: 4
Number of steps: 11
Number of steps: 10
Number of steps: 12
Number of steps: 8
Number of steps: 16
Number of steps: 5
Number of steps: 11
Number of steps: 61
Number of steps: 34
Number of steps: 16
Number of steps: 6
Number of steps: 6
Number of steps: 7
Number of steps: 3
Number of steps: 8
Number of steps: 17
Number of steps: 38
Number of steps: 20
Number of steps: 27
Number of steps: 3
Number of steps: 9
Number of steps: 13
Number of steps: 20
Number of steps: 14
Number of steps: 17
Number of steps: 15
Number of steps: 4
Number of steps: 8
Number of steps: 5
Number of steps: 10
Number of steps: 32
Number of steps: 60
Number of steps: 6
Number of steps: 

Number of steps: 47
Number of steps: 36
Number of steps: 18
Number of steps: 10
Number of steps: 15
Number of steps: 6
Number of steps: 15
Number of steps: 9
Number of steps: 16
Number of steps: 21
Number of steps: 16
Number of steps: 5
Number of steps: 2
Number of steps: 35
Number of steps: 21
Number of steps: 29
Number of steps: 7
Number of steps: 8
Number of steps: 6
Number of steps: 11
Number of steps: 12
Number of steps: 37
Number of steps: 24
Number of steps: 9
Number of steps: 5
Number of steps: 14
Number of steps: 7
Number of steps: 10
Number of steps: 15
Number of steps: 8
Number of steps: 51
Number of steps: 2
Number of steps: 3
Number of steps: 33
Number of steps: 8
Number of steps: 28
Number of steps: 2
Number of steps: 15
Number of steps: 42
Number of steps: 22
Number of steps: 10
Number of steps: 8
Number of steps: 4
Number of steps: 17
Number of steps: 26
Number of steps: 13
Number of steps: 37
Number of steps: 7
Number of steps: 32
Number of steps: 33
Number of steps: 2

Number of steps: 11
Number of steps: 17
Number of steps: 3
Number of steps: 5
Number of steps: 21
Number of steps: 4
Number of steps: 9
Number of steps: 8
Number of steps: 24
Number of steps: 5
Number of steps: 20
Number of steps: 63
Number of steps: 37
Number of steps: 6
Number of steps: 7
Number of steps: 6
Number of steps: 17
Number of steps: 12
Number of steps: 18
Number of steps: 8
Number of steps: 19
Number of steps: 12
Number of steps: 58
Number of steps: 5
Number of steps: 36
Number of steps: 2
Number of steps: 13
Number of steps: 14
Number of steps: 15
Number of steps: 8
Number of steps: 10
Number of steps: 29
Number of steps: 22
Number of steps: 43
Number of steps: 7
Number of steps: 16
Number of steps: 13
Number of steps: 17
Number of steps: 15
Number of steps: 15
Number of steps: 11
Number of steps: 42
Number of steps: 12
Number of steps: 68
Number of steps: 9
Number of steps: 2
Number of steps: 3
Number of steps: 7
Number of steps: 11
Number of steps: 9
Number of steps: 7


Number of steps: 5
Number of steps: 15
Number of steps: 20
Number of steps: 7
Number of steps: 7
Number of steps: 20
Number of steps: 28
Number of steps: 4
Number of steps: 3
Number of steps: 10
Number of steps: 32
Number of steps: 29
Number of steps: 13
Number of steps: 18
Number of steps: 15
Number of steps: 16
Number of steps: 14
Number of steps: 15
Number of steps: 18
Number of steps: 30
Number of steps: 11
Number of steps: 12
Number of steps: 21
Number of steps: 2
Number of steps: 3
Number of steps: 5
Number of steps: 12
Number of steps: 15
Number of steps: 4
Number of steps: 3
Number of steps: 3
Number of steps: 5
Number of steps: 7
Number of steps: 66
Number of steps: 11
Number of steps: 35
Number of steps: 33
Number of steps: 20
Number of steps: 50
Number of steps: 15
Number of steps: 2
Number of steps: 22
Number of steps: 10
Number of steps: 5
Number of steps: 51
Number of steps: 6
Number of steps: 29
Number of steps: 3
Number of steps: 5
Number of steps: 16
Number of steps: 1

Number of steps: 34
Number of steps: 6
Number of steps: 4
Number of steps: 5
Number of steps: 8
Number of steps: 13
Number of steps: 7
Number of steps: 22
Number of steps: 13
Number of steps: 16
Number of steps: 2
Number of steps: 6
Number of steps: 6
Number of steps: 18
Number of steps: 25
Number of steps: 7
Number of steps: 28
Number of steps: 3
Number of steps: 16
Number of steps: 8
Number of steps: 11
Number of steps: 22
Number of steps: 6
Number of steps: 7
Number of steps: 26
Number of steps: 13
Number of steps: 23
Number of steps: 17
Number of steps: 4
Number of steps: 10
Number of steps: 8
Number of steps: 3
Number of steps: 18
Number of steps: 5
Number of steps: 7
Number of steps: 14
Number of steps: 9
Number of steps: 27
Number of steps: 52
Number of steps: 4
Number of steps: 21
Number of steps: 15
Number of steps: 4
Number of steps: 3
Number of steps: 37
Number of steps: 50
Number of steps: 7
Number of steps: 29
Number of steps: 32
Number of steps: 24
Number of steps: 18
Num

Number of steps: 54
Number of steps: 3
Number of steps: 48
Number of steps: 16
Number of steps: 3
Number of steps: 23
Number of steps: 12
Number of steps: 3
Number of steps: 22
Number of steps: 12
Number of steps: 10
Number of steps: 6
Number of steps: 12
Number of steps: 4
Number of steps: 11
Number of steps: 4
Number of steps: 7
Number of steps: 4
Number of steps: 3
Number of steps: 3
Number of steps: 7
Number of steps: 7
Number of steps: 55
Number of steps: 8
Number of steps: 50
Number of steps: 7
Number of steps: 37
Number of steps: 11
Number of steps: 34
Number of steps: 54
Number of steps: 3
Number of steps: 29
Number of steps: 7
Number of steps: 45
Number of steps: 16
Number of steps: 8
Number of steps: 11
Number of steps: 52
Number of steps: 6
Number of steps: 3
Number of steps: 33
Number of steps: 61
Number of steps: 2
Number of steps: 51
Number of steps: 5
Number of steps: 7
Number of steps: 16
Number of steps: 13
Number of steps: 9
Number of steps: 30
Number of steps: 25
Num

Number of steps: 24
Number of steps: 8
Number of steps: 15
Number of steps: 7
Number of steps: 28
Number of steps: 14
Number of steps: 16
Number of steps: 3
Number of steps: 3
Number of steps: 6
Number of steps: 15
Number of steps: 21
Number of steps: 10
Number of steps: 8
Number of steps: 2
Number of steps: 11
Number of steps: 7
Number of steps: 23
Number of steps: 12
Number of steps: 18
Number of steps: 3
Number of steps: 5
Number of steps: 25
Number of steps: 17
Number of steps: 24
Number of steps: 2
Number of steps: 37
Number of steps: 16
Number of steps: 13
Number of steps: 6
Number of steps: 14
Number of steps: 53
Number of steps: 9
Number of steps: 24
Number of steps: 10
Number of steps: 4
Number of steps: 7
Number of steps: 6
Number of steps: 19
Number of steps: 3
Number of steps: 2
Number of steps: 3
Number of steps: 12
Number of steps: 6
Number of steps: 5
Number of steps: 15
Number of steps: 30
Number of steps: 3
Number of steps: 3
Number of steps: 16
Number of steps: 8
Numb

Number of steps: 3
Number of steps: 22
Number of steps: 19
Number of steps: 25
Number of steps: 17
Number of steps: 7
Number of steps: 12
Number of steps: 61
Number of steps: 7
Number of steps: 31
Number of steps: 18
Number of steps: 6
Number of steps: 6
Number of steps: 14
Number of steps: 54
Number of steps: 23
Number of steps: 24
Number of steps: 11
Number of steps: 5
Number of steps: 5
Number of steps: 12
Number of steps: 27
Number of steps: 24
Number of steps: 15
Number of steps: 40
Number of steps: 5
Number of steps: 23
Number of steps: 5
Number of steps: 6
Number of steps: 19
Number of steps: 4
Number of steps: 94
Number of steps: 7
Number of steps: 4
Number of steps: 8
Number of steps: 16
Number of steps: 4
Number of steps: 14
Number of steps: 3
Number of steps: 18
Number of steps: 11
Number of steps: 7
Number of steps: 6
Number of steps: 13
Number of steps: 9
Number of steps: 8
Number of steps: 11
Number of steps: 45
Number of steps: 7
Number of steps: 5
Number of steps: 10
Nu

Number of steps: 34
Number of steps: 9
Number of steps: 6
Number of steps: 17
Number of steps: 17
Number of steps: 11
Number of steps: 12
Number of steps: 11
Number of steps: 23
Number of steps: 4
Number of steps: 21
Number of steps: 8
Number of steps: 14
Number of steps: 4
Number of steps: 29
Number of steps: 2
Number of steps: 16
Number of steps: 30
Number of steps: 3
Number of steps: 43
Number of steps: 27
Number of steps: 10
Number of steps: 5
Number of steps: 3
Number of steps: 20
Number of steps: 8
Number of steps: 9
Number of steps: 5
Number of steps: 6
Number of steps: 23
Number of steps: 3
Number of steps: 17
Number of steps: 5
Number of steps: 2
Number of steps: 3
Number of steps: 8
Number of steps: 5
Number of steps: 3
Number of steps: 8
Number of steps: 6
Number of steps: 28
Number of steps: 23
Number of steps: 33
Number of steps: 40
Number of steps: 18
Number of steps: 40
Number of steps: 7
Number of steps: 43
Number of steps: 26
Number of steps: 2
Number of steps: 8
Numbe

Number of steps: 11
Number of steps: 11
Number of steps: 10
Number of steps: 25
Number of steps: 29
Number of steps: 46
Number of steps: 12
Number of steps: 35
Number of steps: 8
Number of steps: 11
Number of steps: 10
Number of steps: 36
Number of steps: 9
Number of steps: 6
Number of steps: 5
Number of steps: 6
Number of steps: 9
Number of steps: 19
Number of steps: 10
Number of steps: 6
Number of steps: 15
Number of steps: 4
Number of steps: 6
Number of steps: 2
Number of steps: 2
Number of steps: 28
Number of steps: 11
Number of steps: 17
Number of steps: 24
Number of steps: 19
Number of steps: 8
Number of steps: 38
Number of steps: 32
Number of steps: 37
Number of steps: 20
Number of steps: 11
Number of steps: 3
Number of steps: 33
Number of steps: 25
Number of steps: 20
Number of steps: 27
Number of steps: 4
Number of steps: 18
Number of steps: 6
Number of steps: 12
Number of steps: 36
Number of steps: 9
Number of steps: 40
Number of steps: 11
Number of steps: 9
Number of steps: 

Number of steps: 13
Number of steps: 35
Number of steps: 12
Number of steps: 10
Number of steps: 19
Number of steps: 23
Number of steps: 11
Number of steps: 6
Number of steps: 30
Number of steps: 15
Number of steps: 4
Number of steps: 9
Number of steps: 7
Number of steps: 33
Number of steps: 19
Number of steps: 6
Number of steps: 4
Number of steps: 4
Number of steps: 25
Number of steps: 4
Number of steps: 8
Number of steps: 14
Number of steps: 6
Number of steps: 3
Number of steps: 17
Number of steps: 94
Number of steps: 14
Number of steps: 13
Number of steps: 2
Number of steps: 14
Number of steps: 21
Number of steps: 2
Number of steps: 41
Number of steps: 28
Number of steps: 25
Number of steps: 5
Number of steps: 21
Number of steps: 13
Number of steps: 13
Number of steps: 23
Number of steps: 3
Number of steps: 25
Number of steps: 15
Number of steps: 13
Number of steps: 23
Number of steps: 13
Number of steps: 4
Number of steps: 54
Number of steps: 45
Number of steps: 5
Number of steps: 

Number of steps: 44
Number of steps: 54
Number of steps: 30
Number of steps: 27
Number of steps: 17
Number of steps: 11
Number of steps: 17
Number of steps: 25
Number of steps: 10
Number of steps: 6
Number of steps: 44
Number of steps: 17
Number of steps: 6
Number of steps: 56
Number of steps: 22
Number of steps: 9
Number of steps: 10
Number of steps: 9
Number of steps: 3
Number of steps: 5
Number of steps: 14
Number of steps: 23
Number of steps: 13
Number of steps: 2
Number of steps: 26
Number of steps: 50
Number of steps: 64
Number of steps: 30
Number of steps: 2
Number of steps: 24
Number of steps: 13
Number of steps: 29
Number of steps: 6
Number of steps: 3
Number of steps: 16
Number of steps: 13
Number of steps: 6
Number of steps: 5
Number of steps: 5
Number of steps: 3
Number of steps: 14
Number of steps: 12
Number of steps: 4
Number of steps: 17
Number of steps: 6
Number of steps: 11
Number of steps: 3
Number of steps: 7
Number of steps: 8
Number of steps: 12
Number of steps: 19

Number of steps: 13
Number of steps: 35
Number of steps: 28
Number of steps: 3
Number of steps: 6
Number of steps: 32
Number of steps: 20
Number of steps: 3
Number of steps: 7
Number of steps: 6
Number of steps: 7
Number of steps: 9
Number of steps: 14
Number of steps: 15
Number of steps: 13
Number of steps: 24
Number of steps: 7
Number of steps: 26
Number of steps: 6
Number of steps: 23
Number of steps: 7
Number of steps: 6
Number of steps: 39
Number of steps: 4
Number of steps: 40
Number of steps: 28
Number of steps: 21
Number of steps: 20
Number of steps: 2
Number of steps: 13
Number of steps: 11
Number of steps: 15
Number of steps: 9
Number of steps: 41
Number of steps: 13
Number of steps: 5
Number of steps: 14
Number of steps: 6
Number of steps: 9
Number of steps: 10
Number of steps: 12
Number of steps: 6
Number of steps: 14
Number of steps: 5
Number of steps: 30
Number of steps: 9
Number of steps: 41
Number of steps: 13
Number of steps: 5
Number of steps: 35
Number of steps: 32
N

Number of steps: 30
Number of steps: 18
Number of steps: 98
Number of steps: 11
Number of steps: 9
Number of steps: 18
Number of steps: 15
Number of steps: 10
Number of steps: 11
Number of steps: 29
Number of steps: 3
Number of steps: 3
Number of steps: 18
Number of steps: 10
Number of steps: 19
Number of steps: 93
Number of steps: 5
Number of steps: 3
Number of steps: 8
Number of steps: 46
Number of steps: 10
Number of steps: 5
Number of steps: 15
Number of steps: 7
Number of steps: 3
Number of steps: 15
Number of steps: 25
Number of steps: 24
Number of steps: 78
Number of steps: 6
Number of steps: 9
Number of steps: 16
Number of steps: 20
Number of steps: 13
Number of steps: 10
Number of steps: 16
Number of steps: 19
Number of steps: 17
Number of steps: 50
Number of steps: 21
Number of steps: 8
Number of steps: 4
Number of steps: 10
Number of steps: 16
Number of steps: 21
Number of steps: 12
Number of steps: 6
Number of steps: 63
Number of steps: 17
Number of steps: 5
Number of steps

Number of steps: 25
Number of steps: 58
Number of steps: 15
Number of steps: 3
Number of steps: 37
Number of steps: 6
Number of steps: 19
Number of steps: 31
Number of steps: 34
Number of steps: 8
Number of steps: 3
Number of steps: 5
Number of steps: 11
Number of steps: 2
Number of steps: 82
Number of steps: 21
Number of steps: 6
Number of steps: 43
Number of steps: 8
Number of steps: 16
Number of steps: 23
Number of steps: 6
Number of steps: 4
Number of steps: 3
Number of steps: 87
Number of steps: 17
Number of steps: 5
Number of steps: 43
Number of steps: 13
Number of steps: 12
Number of steps: 18
Number of steps: 73
Number of steps: 6
Number of steps: 36
Number of steps: 53
Number of steps: 12
Number of steps: 10
Number of steps: 13
Number of steps: 31
Number of steps: 34
Number of steps: 10
Number of steps: 13
Number of steps: 6
Number of steps: 10
Number of steps: 3
Number of steps: 8
Number of steps: 92
Number of steps: 14
Number of steps: 3
Number of steps: 36
Number of steps: 